### PR TITLE
Fix deblurring when photos are at images-ssl.gotinder.com

### PR DESCRIPTION
**Pull request by aamezua**
Solve deblurring when photos are in images-ssl.gotinder.com

### CODE REVIEW

**Comment by tajnymag** [comment]
Could you, please, try this version?
https://gist.github.com/tajnymag/ba18f441ce28b543a31b379f61ebbe38/raw/3058a5847596c4b1429e6ef1ece5c122a8a303ad/tinder.user.js

I've applied a few brush strokes to your script to make it a bit more readable and concise. I'm not really sure about the logic which handles urls that already contain "preview". It feels wrong to leave them unmodified.

**Comment by aamezua** [comment]
It did not work for urls with "preview" because the if clause was causing the code skipping the cases. I fixed it modifying the if clause. 
Try it in https://github.com/aamezua/tinder-deblur/blob/images-ssl/tinder.user.js

**Comment by tajnymag** [comment]
I know, I know, I'm being late. I just had a VERY busy week. And with Christmas on horizon (almost literally) I'll get to it the earliest on Sunday or Monday.

**Comment by aamezua** [comment]
Oh!! Excuse me. I did not want to be pushy. I am not very familiar with the process (I am sure you noticed) and I was not sure the changes were properly committed.

**Comment by tajnymag** [comment]
You were right, I did skip the cases with `preview` in the image url. So far, there's only two cases that can happen, either the image includes `preview` or `images-ssl`. I refactored the if-else logic into a single if check. I take `preview` as default and reassign it when the case does not suit.

Do I understand it right?

Newly updated version:
https://gist.github.com/tajnymag/ba18f441ce28b543a31b379f61ebbe38

**Comment by aamezua** [comment]
Yes.
I tried and works great!
I believe we can close the issue #12

**Comment by tajnymag** [comment]
Awesome. I'll close it after I push my changes and merge your PR

**Comment by tajnymag** [comment]
Thank you once again. Once the service refreshes its cache, you should be listed as our new contributor at the bottom of the README :)

**Pull request merged**
